In [2]:
import numpy as np

# two dimensional of shape 4x5 uniformly distibuted between 0 and 1

In [12]:
var_2d = np.linspace(0, 1, 20)
print(var_2d)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


# RESHAPING THE ARRAY

In [14]:
var_2d_reshape = var_2d.reshape(4,5)
var_2d_reshape

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

# Generate a np array of vector of length 50

In [15]:
var_1d = np.linspace(0, 1, 50)
print(var_1d)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


# Split the two dimension array into three arrays taking the first two rows, follow by the next two rows and put the remaining in another variable

In [16]:
array1 =var_2d_reshape[:2, :]
print("Array 1:")
print(array1)
print()

Array 1:
[[0.         0.05263158 0.10526316 0.15789474 0.21052632]
 [0.26315789 0.31578947 0.36842105 0.42105263 0.47368421]]



In [18]:
array2 = var_2d_reshape[2:4, :]
print("Array 2:")
print(array2)

Array 2:
[[0.52631579 0.57894737 0.63157895 0.68421053 0.73684211]
 [0.78947368 0.84210526 0.89473684 0.94736842 1.        ]]


In [19]:
array3 = var_2d_reshape[4:, :]
print("Array 3:")
print(array3)

Array 3:
[]


# GENERATE RANDOM NUMBER BETWEEN O AND 1 OF LENGTH 50

In [20]:
var = np.linspace(0,1, 50)
var

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

# SPLITTING THE ARRAY INTO 15, 20 AND 15

In [27]:
x, x1, x2 = np.split(var, (15, 35))
print(x, x1, x2)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429] [0.30612245 0.32653061 0.34693878 0.36734694 0.3877551  0.40816327
 0.42857143 0.44897959 0.46938776 0.48979592 0.51020408 0.53061224
 0.55102041 0.57142857 0.59183673 0.6122449  0.63265306 0.65306122
 0.67346939 0.69387755] [0.71428571 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653
 0.83673469 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551
 0.95918367 0.97959184 1.        ]


In [ ]:
###It is not advisable to use random if you don't want your data to be randomly generated